services:
  # Main Django application
  portal:
    build: ./portal
    ports:
      - "8000:8000"
    volumes:
      - ./portal:/app
      - ./data:/app/data
      - ./logs:/app/logs
      - ./tools:/app/host-tools
      - ./workflow-orchestrator:/app/workflow-orchestrator
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DEBUG=0
      - DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1,[::1],localhost:8000
      - DOCKER_HOST=unix:///var/run/docker.sock
    depends_on:
      - redis
      - postgres
    networks:
      - bioframe-network

  # Redis for task queue and caching
  redis:
    image: redis:7-alpine
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    networks:
      - bioframe-network

  # PostgreSQL for data storage
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=bioframe
      - POSTGRES_USER=bioframe
      - POSTGRES_PASSWORD=bioframe123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - bioframe-network

  # FastQC for quality control
  fastqc:
    build: ./tools/fastqc
    volumes:
      - ./data:/data
      - ./logs:/logs
    environment:
      - THREADS=4
    networks:
      - bioframe-network

  # Trimmomatic for adapter trimming
  trimmomatic:
    build: ./tools/trimmomatic
    volumes:
      - ./data:/data
      - ./logs:/logs
    environment:
      - THREADS=4
    networks:
      - bioframe-network

  # SPAdes for genome assembly
  spades:
    build: ./tools/spades
    volumes:
      - ./data:/data
      - ./logs:/logs
    environment:
      - THREADS=8
      - MEMORY=16
    networks:
      - bioframe-network

  # QUAST for assembly quality assessment
  quast:
    build: ./tools/quast
    volumes:
      - ./data:/data
      - ./logs:/logs
    environment:
      - THREADS=4
    networks:
      - bioframe-network

  # BWA for read mapping
  bwa:
    build: ./tools/bwa
    volumes:
      - ./data:/data
      - ./logs:/logs
    environment:
      - THREADS=4
    networks:
      - bioframe-network

  # SAMtools for SAM/BAM processing
  samtools:
    build: ./tools/samtools
    volumes:
      - ./data:/data
      - ./logs:/logs
    environment:
      - THREADS=4
    networks:
      - bioframe-network

  # BEDtools for genomic analysis
  bedtools:
    build: ./tools/bedtools
    volumes:
      - ./data:/data
      - ./logs:/logs
    environment:
      - THREADS=4
    networks:
      - bioframe-network

  # MultiQC for comprehensive QC reports
  multiqc:
    build: ./tools/multiqc
    volumes:
      - ./data:/data
      - ./logs:/logs
    environment:
      - THREADS=4
    networks:
      - bioframe-network

  # GATK for variant calling
  gatk:
    build: ./tools/gatk
    volumes:
      - ./data:/data
      - ./logs:/logs
    environment:
      - THREADS=4
      - MEMORY=16
    networks:
      - bioframe-network

  # Pilon for assembly improvement
  pilon:
    build: ./tools/pilon
    volumes:
      - ./data:/data
      - ./logs:/logs
    environment:
      - THREADS=4
      - MEMORY=16
    networks:
      - bioframe-network

  # Workflow orchestrator
  workflow-orchestrator:
    build: ./workflow-orchestrator
    volumes:
      - ./data:/data
      - ./workflows:/workflows
      - ./logs:/logs
      - ./tools:/workflow/tools
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
      - BIOFRAME_HOST_PATH=/g/Work File/Projects/BioFrame
    depends_on:
      - portal
    networks:
      - bioframe-network

volumes:
  redis_data:
  postgres_data:

networks:
  bioframe-network:
    driver: bridge